name: Build and Deploy

on:
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la UI de GitHub

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      # Paso 1: Revisar el código fuente
      - name: Check out repository
        uses: actions/checkout@v2
      
      # Paso 2: Configurar Node.js 16
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      # Paso 3: Instalar dependencias de sistema necesarias
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl git

      # Paso 4: Clonar los repositorios y ejecutar la compilación
      - name: Clone repositories and build with Yarn
        run: |
          # Crear directorios necesarios
          mkdir -p /usr/src/app/.bin/dev/tmp

          # Clonar los repositorios
          cd /usr/src/app/.bin/dev/tmp
          git clone "https://github.com/libDrive/server.git" --depth 1 server
          git clone "https://github.com/libDrive/web.git" --depth 1 web

          # Preparar los directorios
          mkdir -p ./libDrive.Server/build ./libDrive.Server/src ./libDrive.Server/templates

          # Instalar dependencias de Yarn y compilar
          cd ./web
          yarn install
          yarn run build

          # Mover los archivos generados
          mv ./build/* ../libDrive.Server/build
          
          # Mover otros archivos necesarios
          cd ../server
          mv main.py requirements.txt ../libDrive.Server
          mv ./src/* ../libDrive.Server/src
          mv ./templates/* ../libDrive.Server/templates
          
          # Copiar archivos adicionales
          cp ../../../README.md ../../../LICENSE ./libDrive.Server

          # Limpiar la estructura final
          mv ./libDrive.Server/* ../..
          cd ../../..

      # Paso 5: Crear un archivo ZIP del build
      - name: Create a ZIP of the build
        run: |
          zip -r build_output.zip ./libDrive.Server

      # Paso 6: Subir el archivo ZIP como artefacto
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-output
          path: build_output.zip
